# Generated by Django 5.2 on 2025-04-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mid', models.CharField(help_text='Movie ID', max_length=20)),
                ('Name', models.CharField(max_length=10)),
                ('Genre', models.CharField(max_length=20)),
                ('Rating', models.IntegerField()),
                ('Collection', models.IntegerField()),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
